name: docker
description: A Dart wrapper around the Docker command line
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-docker.git

version: 0.2.4

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  browser: ^0.10.0

  logging: '>=0.11.3 <1.0.0'

  validate: ^1.0.0

dev_dependencies:
  test: any
  grinder: any